name: api-gateway-cron

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [api-gateway-cron-trigger]

jobs:
  api-gateway-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: api-gateway-cron
        run: uv run python main.py

      - name: http-log
        run: uv run python http-log.py
